import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-sistema-endocrino',
  templateUrl: './sistema-endocrino.page.html',
  styleUrls: ['./sistema-endocrino.page.scss'],
})
export class SistemaEndocrinoPage {
  public items: any = [];

  constructor() {
    this.items = [
      { expanded: false,titulo:"RESUMO",imagem:"", referenciaImagem:"",texto:"O sistema endócrino é composto por um conjunto de glândulas endócrinas, responsáveis por secretar hormônios diretamente nos líquidos corporais (sangue e linfa), contribuindo para a homeostasia regulando a atividade e o crescimento de células-alvo no corpo, bem como o metabolismo. As principais glândulas endócrinas do corpo humano são: hipófise, glândula tireóidea, glândulas paratireóideas, pâncreas, suprarrenais e as gônadas (ovários e testículos) [1], [2]."},
      { expanded: false,titulo:"GLÂNDULAS ENDÓCRINAS",titulo2:"E REGULAÇÃO HORMONAL",imagem:"",referenciaImagem:"",texto:"Grande parte do funcionamento do organismo depende da comunicação entre as células com mensageiros químicos. As <strong>glândulas endócrinas</strong> são responsáveis por secretar seus produtos (os hormônios) no líquido intersticial que circunda as células, sendo difundidos para a corrente sanguínea ou linfática [1], [4].<br><br>Vale ressaltar a diferença das <strong>glândulas endócrinas</strong> das <strong>glândulas exócrinas</strong>. . Estas, por sua vez, secretam seus produtos em ductos que os direciona para cavidades corporais ou superfície externa do corpo, como, por exemplo, as glândulas digestivas (sucos digestivos) e glândulas sudoríparas (suor) [4].<br><br>Sendo assim, o <strong>conjunto de glândulas endócrinas</strong> do corpo humano constitui o <strong>sistema endócrino</strong>, sendo as principais delas hipófise, glândula tireóidea, glândulas paratireóideas, pâncreas, suprarrenais e as gônadas (ovários e testículos) [1].",imagem2:"assets/imagensCorpo/teoria1endo.png",referenciaImagem2:"Imagem: Adaptada de MrArifnajafov, <a href=https://creativecommons.org/publicdomain/mark/1.0/deed.pt_BR>, Domínio Público</a>, via Wikimedia Commons. Disponível <a href=https://commons.wikimedia.org/wiki/File:Illu_endocrine_system-az.jpg>aqui.</a>",texto3:"Dependendo do hormônio produzido pelas glândulas endócrinas, podem ser classificados por suas funções desempenhadas, que podem ser: <strong>metabólicas</strong> (controlam a velocidade das reações químicas), <strong>morfogenéticas</strong> (regulam o crescimento e o desenvolvimento de certos órgãos), <strong>sexuais</strong> e <strong>reprodutivas</strong> (desenvolvimento de caracteres sexuais morfológicos, fisiológicos e psicológicos) ou <strong>nervosas</strong> e <strong>mentais</strong> (influem sobre a formação da personalidade) [3].<br><br>A regulação endócrina é realizada por um mecanismo denominado <strong>retroalimentação</strong> ou <strong>feedback</strong>, ou seja, o nível de determinado hormônio no sangue determina a estimulação ou inibição da atividade de sua respectiva glândula [3].<br><br>Esse mecanismo pode ser chamado de positivo ou negativo. O feedback é <strong>positivo</strong> quando a concentração final de um determinado hormônio estimula sua própria produção. O feedback é <strong>negativo</strong> quando a concentração final de um determinado hormônio reduz sua própria produção [3]."},
      { expanded: false,titulo:"HIPÓFISE",imagem:"",referencia:"",texto:"A hipófise é conhecida como “glândula mestra”, tendo em vista que é responsável por controlar a função da maioria das outras glândulas endócrinas. Tem relação direta com o <strong>hipotálamo</strong> (órgão do sistema nervoso central, localizada no encéfalo), que ao receber informações trazidas por nervos, secreta hormônios que atuam sobre a hipófise [1].",imagem2:"assets/imagensCorpo/teoria2endo.png",referenciaImagem2:"Imagem: Adaptada de Servier Medical Art, <a href=https://creativecommons.org/licenses/by/3.0/>(Creative Commons 3.0).</a> Disponível <a href=https://smart.servier.com/image-set-download/>aqui.</a>",texto2:"A hipófise é constituída por dois tipos de células endócrinas: a <strong>adenoipófise</strong> e a <strong>neuroipófise</strong>.<br><br>A porção anterior, é denominada <strong>adenoipófise</strong> e origina-se de um tecido epitelial como a maioria das outras glândulas endócrinas. Essa porção da hipófise é responsável por produzir e liberar no sangue diversos hormônios, entre eles os chamados hormônios tróficos, cujo efeito é estimular o funcionamento de outras glândulas endócrinas [1].<br><br>A liberação de hormônios da adenoipófise é estimulada por <strong>hormônios liberadores</strong> e suprimida por <strong>hormônios inibidores</strong> do hipotálamo. Assim, os hormônios hipotalâmicos constituem uma ligação importante entre os sistemas nervoso e endócrino [4].<br><br> A porção posterior, é denominada <strong>neuroipófise</strong> e consiste em um prolongamento do hipotálamo constituído por neurônios modificados, tendo, portanto, origem nervosa. Essa porção, armazena e libera dois hormônios produzidos pelo hipotálamo [1].",imagem3:"assets/imagensCorpo/teoria3endo.png"},
      { expanded: false,titulo:"TIREÓIDE E",titulo2:"PARATIREÓIDES",imagem:"assets/imagensCorpo/teoria4endo.png",referenciaImagem:"Imagem: Adaptada de Servier Medical Art, <a href=https://creativecommons.org/licenses/by/3.0/>(Creative Commons 3.0).</a> Disponível <a href=https://smart.servier.com/image-set-download/>aqui.</a>",texto:"A <strong>glândula tireóidea</strong> é uma glândula em formato de borboleta que está localizada no pescoço, abaixo das cartilagens da laringe e sobre a porção inicial da traqueia. É a única glândula endócrina que <strong>armazena seu produto secretório</strong> em grandes quantidades, geralmente o suficiente para 100 dias [1], [4].<br><br>Os principais hormônios da glândula tireoide são a tri-iodotironina <strong>(T3)</strong> e a tiroxina <strong>(T4)</strong>. Além destes, outro importante hormônio da tireoide é a <strong>calcitonina</strong>. A glândula tireoide desempenha papel fundamental na homeostase do organismo, de modo que os hormônios produzidos por ela ajudam a manter normais a pressão sanguínea, ritmo cardíaco, tônus muscular e funções sexuais [1].<br><br>As <strong>glândulas paratireoides</strong>, por sua vez, estão em número de quatro e são pequenas massas de tecido arredondadas aderidas à porção posterior da tireoide. Elas produzem o hormônio paratormônio [1], [4].",imagem2:"assets/imagensCorpo/teoria5endo.png",referenciaImagem2:"",texto2:"Se uma pessoa sofrer <strong>disfunção das glândulas paratireoides</strong> e consequente redução do paratormônio, terá diminuição do cálcio no sangue, podendo levar as células musculares esqueléticas a se contrair convulsivamente, havendo a necessidade de tratamento com paratormônio ou cálcio. Caso contrário, pode ocorrer contração intermitente dos músculos (tetania muscular) e até a morte [1]."},
      { expanded: false,titulo:"PÂNCREAS",imagem:"",referenciaImagem:"",texto:"O pâncreas é uma glândula mista, isto é, que desempenha tanto <strong>função endócrina</strong> como <strong>exócrina</strong>. Em sua função exócrina, o pâncreas constitui-se como órgão do sistema digestivo humano [1], [2]. <br><br>Em sua função endócrina, o pâncreas é constituído por aglomerados celulares denominados <strong>ilhotas pancreáticas</strong>, formadas por <strong>células-alfa</strong>, responsáveis pela produção do hormônio <strong>glucagon</strong>, e por <strong>células-beta</strong>, responsáveis pela produção de <strong>insulina</strong> [1].",imagem2:"assets/imagensCorpo/teoria6endo.png",referenciaImagem2:"Imagem: Adaptada de Servier Medical Art, <a href=https://creativecommons.org/licenses/by/3.0/>(Creative Commons 3.0).</a>  Disponível <a href=https://smart.servier.com/image-set-download/>aqui.</a>",texto2:"Os hormônios produzidos pelo pâncreas estão relacionados ao <strong>controle da taxa de glicose no sangue</strong> Assim, após uma refeição, a glicose no sangue aumenta, o que promove o estímulo das células-beta a secretarem <strong>insulina</strong>. . Sob a ação desse hormônio, todas as células passam a absorver mais glicose, o que diminui sua concentração [1].<br><br>Caso contrário, se uma pessoa fica muitas horas sem se alimentar, a concentração de glicose em seu sangue diminui e as células-alfa são estimuladas a secretar <strong>glucagon</strong>. Sob a ação desse hormônio, o fígado passa a converter glicogênio em glicose, liberando esse açúcar no sangue [1].",imagem3:"assets/imagensCorpo/teoria7endo.png"},
      { expanded: false,titulo:"SUPRARRENAL",imagem:"",referenciaImagem:"",texto:"As <strong>glândulas suprarrenais</strong> (ou adrenais) são duas, uma localizada acima de cada rim. São constituídas por dois tecidos secretores distintos de ponto de vista estrutural e funcional: o córtex da glândula suprarrenal, que compreende 80 a 90% da glândula, e uma pequena <strong>medula</strong> da glândula suprarrenal, localizada mais internamente [1], [4].",imagem2:"assets/imagensCorpo/teoria8endo.png",referenciaImagem2:"Imagem: Adaptada de Servier Medical Art, <a href=https://creativecommons.org/licenses/by/3.0/>(Creative Commons 3.0).</a>  Disponível <a href=https://smart.servier.com/image-set-download/>aqui.</a>",texto2:"O <strong>córtex</strong> da glândula suprarrenal produz hormônios <strong>esteroides</strong> essenciais a vida, conhecidos genericamente como corticosteroides. Dentre os grupos desses hormônios, destacam-se os glicocorticoides e os mineralocorticoides [1], [4]. <br><br>Os <strong>glicocorticoides</strong> atuam na produção de glicose a partir de proteínas e gorduras, aumentando os níveis de glicose no sangue, a fim de ser utilizado como combustível em casos de resposta a uma situação estressante. Os <strong>mineralocorticoides</strong>, , por sua vez, regulam o balanço de água e sais, como o sódio e potássio, no organismo [1].<br><br>A <strong>medula</strong> da glândula suprarrenal produz hormônios do tipo catecolaminas, sendo dois principais: a adrenalina (epinefrina) e a noradrenalina (norepinefrina) [4].<br><br>A <strong>adrenalina</strong> é liberada no sangue em situações de estresse (susto, grande emoção, situação de perigo, etc.). Sob a ação deste hormônio, os vasos sanguíneos contraem-se, o sangue passa a se concentrar nos músculos e órgãos internos, os batimentos cardíacos e a pressão arterial aumentam, preparando o organismo para uma resposta vigorosa [1].<br><br>A <strong>noradrenalina</strong>, por sua vez, é liberada em doses mais ou menos constantes pela medula da glândula suprarrenal, independentemente da liberação de adrenalina, tendo como função manter a pressão sanguínea em níveis adequados [1].",imagem3:"assets/imagensCorpo/teoria9endo.png",texto3:"O principal <strong>glicocorticoide</strong> é o <strong>cortisol</strong>, que além de seus efeitos no metabolismo de glicose, diminui a permeabilidade dos capilares sanguíneos, sendo, por isso, utilizada como tratamento de inflamações (processos alérgicos). Contudo, seu uso prolongado pode deprimir o sistema imunitário, tornando o organismo mais suscetível a infecções. Além disso, níveis elevados de cortisol podem ocorrer devido ao estresse crônico, contribuindo, além do enfraquecimento imunológico, para o aparecimento de doenças como úlcera péptica, hipertensão, arteriosclerose e até mesmo câncer. [1]."},
      { expanded: false,titulo:"GÔNADAS",imagem:"",refertenciaImagem:"",texto:"As <strong>gônadas</strong> consistem nos <strong>testículos</strong> (masculino) e nos ovários (feminino) que, além de produzir gametas, produzem hormônios que afetam o crescimento e desenvolvimento do corpo, controlando o ciclo reprodutivo e o comportamento sexual. Esses hormônios são chamados de <strong>hormônios sexuais</strong> [1].",imagem2:"assets/imagensCorpo/teoria10endo.png",referenciaImagem2:"Imagem: Adaptada de Servier Medical Art, <a href=https://creativecommons.org/licenses/by/3.0/>(Creative Commons 3.0).</a>  Disponível <a href=https://smart.servier.com/image-set-download/>aqui.</a>",texto2:"Na mulher, as células do folículo ovariano em desenvolvimento produzem o hormônio <strong>estrógeno.</strong> Outro hormônio sexual feminino, a <strong>progesterona</strong> é produzida principalmente pelo corpo amarelo (lúteo) ovariano, resultante do rompimento do folículo. Nos homens, o principal hormônio sexual masculino (andrógeno) é a testosterona, produzida pelas células intersticiais do testículo [1].",imagem3:"assets/imagensCorpo/teoria11endo.png",texto3:"Durante a <strong>gravidez</strong>, após cerca de dez dias após a fecundação, um hormônio denominado <strong>gonadotrofina coriônica</strong> é produzido pelas vilosidades coriônicas da placenta. A presença deste hormônio na mulher grávida estimula a atividade do corpo lúteo, mantendo elevadas as taxas de estrógeno e progesterona, mantendo a mucosa uterina durante a gravidez [1].<br><br>Os níveis deste hormônio são mantidos, cerca de até o quarto mês, pelo corpo amarelo. Após esse período, o corpo lúteo regride e a placenta assume a função de produzir estrógeno e progesterona, mantendo seus níveis ideais durante a gestação [1]."},
      { expanded: false,titulo:"REFERÊNCIAS",referenciaFim:"[1] AMABIS, J. M. MARTHO, G. R. <strong>Biologia dos organismos</strong>. Volume 2. 3. Ed. São Paulo: Moderna, 2010.<br><br>[2] MENDONÇA, V. L. <strong>Biologia:</strong> o ser humano, genética e evolução. Volume 3. 2. Ed. São Paulo: Editora AJS, 2013.<br><br>[3] PICOLI, L. S. <strong>Controle hormonal</strong> – 6 dúvidas frequentes sobre o assunto. In: Manipulae. 2019. Disponível <a href=https://manipulae.com.br/artigos/controle-hormonal-duvidas>aqui.</a><br><br>[4] TORTORA, G. J.; DERRICKSON, B. <strong>Princípios de Anatomia e Fisiologia</strong>. Tradução Ana Cavalcanti C. Botelho... [et al.]. 14. ed. – Rio de Janeiro: Guanabara Koogan, 2016."}
    ];
  }

  expandItem(item): void {
    if (item.expanded) {
      item.expanded = false;
    } else {
      this.items.map(listItem => {
        if (item == listItem) {
          listItem.expanded = !listItem.expanded;
        } else {
          listItem.expanded = false;
        }
        return listItem;
      });
    }
  }

  visible = false;
  toggle() {
   this.visible = !this.visible;
  }
}
