import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-defesas-corpo',
  templateUrl: './defesas-corpo.page.html',
  styleUrls: ['./defesas-corpo.page.scss'],
})
export class DefesasCorpoPage {
  public items: any = [];

  constructor() {
    this.items = [
      { expanded: false,titulo:"AS DEFESAS",titulo2:" CORPORAIS",imagem:"",referenciaImagem:"",texto:"As células de defesa de nosso organismo estão presentes na circulação sanguínea e linfática. Essas células constituem o que costumamos chamar de <strong>sistema imunológico</strong>, que é composto por certos tipos de leucócitos (glóbulos brancos), sendo principalmente linfócitos e pelos órgãos linfoides [2] (ver “Órgãos Linfoides” em “Distrito Linfático”).</p>                                                                       A função dos leucócitos é defender o organismo contra microrganismos invasores ou substâncias estranhas que penetram nos tecidos. Em uma infecção, por exemplo, o número de leucócitos se multiplicam, podendo dobrar ou triplicar. Esses leucócitos podem ser de cinco tipos básicos: <strong>linfócitos, neutrófilos, eosinófilos, basófilos e monócitos</strong>[1].</p>",imagem2:"assets/imagensCorpo/teoriasc14.png",referenciaImagem2:"Imagem: Adaptada de Servier Medical Art, <a href=https://creativecommons.org/licenses/by/3.0/>(Creative Commons 3.0)</a>.Disponível <a href=https://smart.servier.com/image-set-download/>aqui.</a>"},
      { expanded: false,titulo:"LINFÓCITOS",imagem:"assets/imagensCorpo/teoriasc15.png",referenciaImagem:"Imagem: Adaptada de Servier Medical Art, <a href=https://creativecommons.org/licenses/by/3.0/>(Creative Commons 3.0)</a>.Disponível <a href=https://smart.servier.com/image-set-download/>aqui.</a>",texto:"Os linfócitos são células de forma esférica com núcleo esférico, e são os principais “soldados” de defesa do organismo, dos quais existem vários tipos, que podem ser classificados em linfócitos B ou linfócitos T. Os <strong>linfócitos B</strong> são especializados na produção de <strong>anticorpos</strong>,isto é, proteínas do tipo imunoglobinas que reconhecem e combatem microrganismos e corpos estranhos. Os <strong>linfócitos T</strong>, por sua vez, podem ser de três tipos, sendo eles: <strong>linfócito T citotóxico</strong>, que reconhecem e matam células alteradas (infectadas por vírus, por exemplo); <strong>linfócito T auxiliador</strong>, que recebem informações dos macrófagos sobre a presença de invasores e estimulam os linfócitos B e T citotóxicos a combaterem os invasores; e <strong>linfócito T regulador</strong>, que tem função moduladora na resposta imunitária, podendo refrear a ação dos linfócitos T auxiliadores e citotóxicos [1], [2]. "},
      { expanded: false,titulo:"NEUTRÓFILOS",imagem:"assets/imagensCorpo/teoriasc16.png",referenciaImagem:"Imagem: Adaptada de Servier Medical Art, <a href=https://creativecommons.org/licenses/by/3.0/>(Creative Commons 3.0)</a>.Disponível <a href=https://smart.servier.com/image-set-download/>aqui.</a>",texto:"Os neutrófilos são células de forma esférica com núcleo trilobado. Sua principal função é fagocitar (englobar para dentro de si) bactérias e outros microrganismos que invadem o corpo humano. Essas células são particularmente ativas no início de uma infeção e o pus que se forma em um ferimento infeccionado contém grande quantidade de neutrófilos que morreram durante o processo de defesa [1]. "},
      { expanded: false,titulo:"EOSINÓFILOS",imagem:"assets/imagensCorpo/teoriasc17.png",referenciaImagem:"Imagem: Adaptada de Servier Medical Art, <a href=https://creativecommons.org/licenses/by/3.0/>(Creative Commons 3.0)</a>.Disponível <a href=https://smart.servier.com/image-set-download/>aqui.</a>",texto:"Os eosinófilos, também conhecidos como acidófilos, são células de forma esférica com núcleo bilobado. Sua principal função é combater invasores de grande tamanho, como vermes e parasitas, participando do processo de reações alérgicas e na produção de histamina (substância ativa na resposta imunitária alérgica localizada). A histamina provoca aumento da permeabilidade dos capilares sanguíneos, facilitando a saída de anticorpos e neutrófilos para os locais onde estão os invasores a serem combatidos [1]. "},
      { expanded: false,titulo:"BASÓFILO",imagem:"assets/imagensCorpo/teoriasc18.png",referenciaImagem:"Imagem: Adaptada de Servier Medical Art, <a href=https://creativecommons.org/licenses/by/3.0/>(Creative Commons 3.0)</a>.Disponível <a href=https://smart.servier.com/image-set-download/>aqui.</a>",texto:"Os basófilos são células esféricas de núcleo irregular. Apesar de sua função não ser bem conhecida, sabe-se que os basófilos liberam histamina e heparina. A histamina provoca aumento da permeabilidade dos capilares sanguíneos, facilitando a saída de anticorpos e neutrófilos para os locais onde estão os invasores a serem combatidos. A heparina consiste em um polissacarídeo com propriedades anticoagulantes [1].  "},
      { expanded: false,titulo:"MONÓCITO",imagem:"assets/imagensCorpo/teoriasc19.png",referenciaImagem:"Imagem: Adaptada de Servier Medical Art, <a href=https://creativecommons.org/licenses/by/3.0/>(Creative Commons 3.0)</a>.Disponível <a href=https://smart.servier.com/image-set-download/>aqui.</a>",texto:"Os monócitos são células de forma esférica e com núcleo oval ou riniforme. Quando estão no sangue, essas células são chamadas monócitos, porém, após serem formados na medula óssea, eles permanecem no sangue por poucas horas e migram para os tecidos, onde amadurecem e passam a ser chamados de <strong>macrófagos</strong>. A partir de então, passam a apresentar atividade fagocitária, isto é, a ingestão de microrganismos, restos de células mortas, resíduos celulares, etc.  [1], [2]. "},
      { expanded: false,titulo:"IMUNIDADE HUMORAL E",titulo2:"IMUNIDADE CELULAR",imagem:"",referenciaImagem:"",texto:"As defesas do nosso organismo combatem agentes invasores de duas maneiras: por meio da imunidade humoral e por meio da imunidade celular.<br><br> A <strong>imunidade humoral</strong> é aquela em que participam proteínas específicas presentes no plasma sanguíneo: os <strong>anticorpos</strong>. Estes são produzidos pelos linfócitos B maduros ou plasmócitos, e consistem em proteínas que se ligam ao antígeno (substância estranha ao organismo), inativando-os e favorecendo a sua destruição [2], [5].<br><br> A <strong>imunidade celular</strong> é aquela em que não há a participação de anticorpos, sendo mediada diretamente pelas células, tais como os linfócitos T citotóxicos, que reconhecem células anormais ou infectadas e, por meio de liberação de substâncias perfura a membrana plasmática dessas células alteradas, matando-as [2].<br><br>No processo de resposta imune, os linfócitos B e T são ativados, se multiplicam e exercem suas funções, de modo que, durante o processo de ativação e multiplicação dos linfócitos, estes podem se diferenciar em <strong>células de memória</strong>, que guardam por anos a informação do antígeno para reconhece-los a ataca-los imediatamente, em caso de novo contato com o invasor [2], [5]."},
      { expanded: false,titulo:"IMUNIZAÇÃO ATIVA E",titulo2:" PASSIVA",imagem:"",referenciaImagem:"",texto:"Existem dois tipos de imunização, ou seja, de formas de proteger o organismo da invasão de substâncias estranhas. Essas formas são conhecidas como <strong>imunização ativa e imunização passiva</strong>, sendo mediadas por vacinas e soros, respectivamente.</p>                                                                       A <strong>imunização ativa</strong> ocorre por meio da vacinação, que consiste na aplicação de antígenos isolados ou atenuados, isto é, tratados de modo que não causem a doença em questão. Isso permite ativar o sistema imunitário e a formação de células de memória. Caso o organismo seja invadido por esse microrganismo, o organismo reagirá de forma mais rápida e intensa, e as células de defesa o destruirão antes mesmo de manifestar os sintomas da doença [2], [5]. </p>                                                                       A <strong>imunização passiva</strong> ocorre por meio de aplicação de soro imune, que consiste em uma solução com anticorpos contra a doença. Os soros imunes são muito utilizados em casos de picadas de cobra ou outros animais peçonhentos, mas recentemente tem sido estudado e cogitado para doenças como, por exemplo, a Covid-19. Contudo, a aplicação do soro confere imunidade temporária, pois a memória imunitária não é estimulada. Essa forma de imunização é fundamental para casos em que não há tempo para esperar a resposta imune do organismo, uma vez que os anticorpos aplicados atacarão diretamente os antígenos patológicos [2], [5]. </p>"},
      { expanded: false,titulo:"REFERÊNCIAS ",referenciaFim:"[1] AMABIS, J. M.; MARTHO, G. R. Biologia: <strong>Biologia</strong> das células. 3ª ed. São Paulo: Moderna, 2010. </p>                                                                       [2] AMABIS, J. M.; MARTHO, G. R. Biologia: Biologia dos organismos. 3ª ed. São Paulo: Moderna, 2010. </p>                                                                       [3] LOURENÇO, R. <strong>Camadas do coração</strong>. 2021. Disponível <a href=https://www.kenhub.com/pt/library/anatomia/camadas-do-coracao>aqui</a>. Acesso em 6 abr. 2021. </p>                                                                       [4] MAGALHÃES, L. Linfa. In: Toda Matéria. [s.d]. Disponível <a href=https://www.todamateria.com.br/linfa/>aqui</a>. Acesso em 6 abr. 2021. </p>                                                                       [5] MENDONÇA, V. L. <strong>Biologia</strong>: o ser humano, genética, evolução. 2ª ed. São Paulo: Editora AJS, 2013. </p>                                                                       [6] SANTOS, V. S. <strong>Tipos de circulação sanguínea</strong>. In: Brasil Escola. [s.d]. Disponível <a href=https://brasilescola.uol.com.br/biologia/tipos-circulacao-sanguinea.htm>aqui.</a> Acesso em: 06 abr. 2021.<br><br>[7] USP. <strong>Sistema de condução</strong>. Capacitação parada cardiorrespiratória adulto. [s.d]. Disponível <a href=http://www2.eerp.usp.br/Nepien/PCR/car_conducao.html>aqui</a>. Acesso em: 06 abr. 2021."}
    ];
  }

  expandItem(item): void {
    if (item.expanded) {
      item.expanded = false;
    } else {
      this.items.map(listItem => {
        if (item == listItem) {
          listItem.expanded = !listItem.expanded;
        } else {
          listItem.expanded = false;
        }
        return listItem;
      });
    }
  }

  visible = false;
  toggle() {
   this.visible = !this.visible;
  }
}